version: 2.1

jobs:
  build:    
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 ./src/index.py
  test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 ./src/index.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
