version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:    
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 ./src/index.py
      - run: python3 ./src/demo.py
  test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: sudo pip install codecov
      - run: sudo pip install -U pytest
      - run: sudo pip install pytest-cov
      - run: sudo pytest --cov=./ --cov-report=xml:reports/coverage.xml
      - run: python3 ./src/test_index.py
      - run: python3 ./src/test_demo.py
      - codecov/upload:
          file: './reports/coverage.xml'
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
