version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  
jobs:
  build:    
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 ./src/index.py
      - run: python3 ./src/demo.py
  test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 ./src/test_index.py
      - run: python3 ./src/test_demo.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
